### ISSUE TITLE
[Feature Request] Argument option to only create markdown for modules/functions with comment blocks

### ISSUE THREAD

**Issue by AshleyJamesy** [TurtleP/luaprettydoc#3]
Currently the tool creates markdown for all modules/functions, however some functions may not be necessary in markdown.
Add an argument option so that you can create markdown only for those with comment blocks.

An alternative is to have an '@exclude' for module/functions you wish to exclude if not using the above argument option

Preferably both options would be good.

Thanks!

**Comment by TurtleP** [comment]
I think listing out the functions would get tiresome via cli. However, even in a configuration file style it might be tedious. Definitely thinking the best route is an `@exclude` tag.

**Comment by TurtleP** [comment]
This was added in commit 2b8966b. I'm open to having a configuration file to list functions as well, but we'll see how this goes for now.

**Comment by AshleyJamesy** [comment]
I was thinking a command line argument like so:

luaprettydocs -o .

Which would only create markdown for lua files which have the "@module" comment block at the start of the file. And then it would only include functions with comment blocks for that module.

This way you don't need to comment every function you want to exclude with "@exclude" which could get tiresome

**Comment by TurtleP** [comment]
Hm.. that makes *some* sense. I think `-m` might work better in that case (since `-o` is usually for output to something in other programs, e.g `tex3ds input.png -o output.t3x`). 

Regardless, I'll see about adding this as well. The tag can be useful, however, since if it's an internal-use only function, for example, you can omit its documentation.

**Comment by TurtleP** [comment]
Okay, I've added `--headers` to the command line arguments. This does exactly what you'd expect.

**Comment by AshleyJamesy** [comment]
Nice!
