### ISSUE TITLE
[Issue] Only one markdown file is created if another lua file exists with same name in different folder

### ISSUE THREAD

**Issue by AshleyJamesy** [TurtleP/luaprettydoc#4]
Tool does not recreate folder structure, 

Since all markdowns are created in /docs/, having multiple files with same name in different folders only creates one markdown file. Probably because it is overwritten.

**Comment by TurtleP** [comment]
Fixed in 01feaa42c199d862a73a145a96edfccdbff4243d. I also changed the output directory to always be the current one, since that makes more sense.
