### ISSUE TITLE
[Feature Request] Overridable Function Definitions

### ISSUE THREAD

**Issue by AshleyJamesy** [TurtleP/luaprettydoc#5]
Currently functions are automatically added to markdown. Add a '@definition' or something similar to make the function definition overridable.

eg: markdown creates
`matrix.copy(a, b) --for convenience we use a, b`

However I might want to show it as this in markdown:
`matrix:copy(b) --in reality we'd call it like this`

so I'd comment my code as such

```lua
--[[
- @definition class:copy(b)
- @brief copies matrix values from another matrix
- @param a:`math.matrix` the matrix to copy into
- @param b:`math.matrix` the matrix to copy from
- @return `math.matrix` matrix `a` copied from `b`
]]
function class.copy(a, b)
	a[ 1] = b[ 1]
	a[ 2] = b[ 2]
	a[ 3] = b[ 3]
	a[ 4] = b[ 4]
	a[ 5] = b[ 5]
	a[ 6] = b[ 6]
	a[ 7] = b[ 7]
	a[ 8] = b[ 8]
	a[ 9] = b[ 9]
	a[10] = b[10]
	a[11] = b[11]
	a[12] = b[12]
	a[13] = b[13]
	a[14] = b[14]
	a[15] = b[15]
	a[16] = b[16]

	return a
end
```

**Comment by TurtleP** [comment]
Added in commit cfe552e.
