### ISSUE TITLE
[Feature Request]: Specify file or directory for tool to run on

### ISSUE THREAD

**Issue by AshleyJamesy** [TurtleP/luaprettydoc#9]
### Enhancement Details

Tool will only run on a specific file or directory

### Solution

A new argument

### Additional Context

Currently I can cd into my project folder and run luaprettydoc
eg:
```
cd project
ls
    src
    main.lua
    conf.lua

luaprettydoc
```

and it will create markdown for any lua files in the project folder and subfolders
I think another argument would be good for specifying the file OR directory eg:

FILE:
```
cd project
luaprettydoc -f "src/core/math/matrix.lua"
```

DIRECTORY:
```
cd project
luaprettydoc -f "src" -s
```
"s" could be for including all subfolders, or another argument to not include subfolders, up to you

**Comment by TurtleP** [comment]
I added this in commit dd4a8ae. Note that this includes breaking changes to the file metadata output. I tried to avoid doing that until I got #7 in place, but bleh.

You can now either pass `--dir` or `--file` to the args and it will only run for the directory or file. `--dir` is recursive, though. I didn't see much reason to not allow it stay this way. If you have some points as to why you'd like it to not recurse, let me know.
